daily_interval: 1d
daily_period: 30y
fetch_mt5: true
initial_balance: 1000
invest_per_week: 100
leverage: 1000
min_years_required: 1
output_directory: .
std_multiplier: 3
symbol_coefficients:
  AAPL.NAS: 1.0
  AAVEUSD: 0.50147
  ABBV.NYSE: 1.0
  ABNB.NAS: 1.0
  ABT.NYSE: 1.0
  ACN.NYSE: 1.0
  ADAUSD: 100.0
  ADBE.NAS: 1
  ADS.XE: 2.00022
  AI.EPA: 1.12698
  AIR.EPA: 1.12766
  ALGOUSD: 274.19355
  ALV.XE: 1
  AMD.NAS: 1.0
  AMZN.NAS: 1
  APTUSD: 12.01028
  ASML.EAS: 1.1
  ATOMUSD: 12.53247
  AUDCAD: 718.23145
  AUDCHF: 1201.9774
  AUDJPY: 6.87684
  AUDNZD: 590.56133
  AUDUSD: 1000.0
  AUS200: 0.06
  AVAXUSD: 3.00325
  AVGO.NAS: 1.0
  AXP.NYSE: 1
  AXSUSD: 2.51515
  AZN.LSE: 1.32993
  BA.NYSE: 1
  BABA.NYSE: 1
  BAC.NYSE: 2.0
  BARC.LSE: 38.4
  BATS.LSE: 3.98936
  BAYN.FWB: 3.0
  BBVA.BM: 6.75547
  BCHUSD: 0.10013
  BEI.XE: 1.0006
  BHP.ASX: 5.13544
  BKNG.NAS: 1
  BLK.NYSE: 1
  BMW.XE: 1.08696
  BMY.NYSE: 3.0
  BNBUSD: 0.09992
  BNP.EPA: 1.11913
  BTCUSD: 0.01
  BX.NYSE: 1.0
  CABK.BM: 1.08
  CADCHF: 1203.20856
  CADJPY: 6.876
  CAT.NYSE: 1
  CBA.ASX: 1.28448
  CHFJPY: 6.88113
  CMCSA.NAS: 7.0
  COP.NYSE: 4.0
  COST.NAS: 1
  CPTL.SGX: 0.76
  CRM.NYSE: 1
  CSCO.NAS: 2.0
  CSL.ASX: 0.64068
  CVS.NYSE: 2.0
  CVX.NYSE: 2.0
  DAII.TSE: 0.07573
  DASHUSD: 3.0
  DHR.NYSE: 2.0
  DIS.NYSE: 1.0
  DKI.TSE: 0.01376
  DOGEUSD: 1000
  DOTUSD: 12.55556
  DTE.FWB: 1
  DTG.FWB: 18
  ENEL.MIL: 3.35196
  ENI.MIL: 10.13393
  ESP35: 0.1
  ETCUSD: 2.51055
  ETHUSD: 0.1
  EURAUD: 641.09261
  EURCAD: 716.90412
  EURCHF: 1202.95203
  EURGBP: 1330.14954
  EURJPY: 6.8727
  EURMXN: 51.42637
  EURNZD: 590.75816
  EURUSD: 1000.0
  EURZAR: 54.9347
  EUSTX50: 0.1
  FETUSD: 30.03
  FILUSD: 20.0
  FRA40: 0.11236
  GBPAUD: 641.10033
  GBPCAD: 717.55119
  GBPCHF: 1202.29682
  GBPJPY: 6.88017
  GBPMXN: 51.43777
  GBPNZD: 592.34869
  GBPUSD: 1000.0
  GBPZAR: 54.93286
  GE.NYSE: 1
  GER40: 0.1
  GOOGL.NAS: 3.0
  GS.NYSE: 1
  HD.NYSE: 1
  HEIA.EAS: 2.26804
  HIT.TSE: 0.007
  HMC.NYSE: 2.0
  HON.NAS: 1
  HSBA.LSE: 7.97654
  IBM.NYSE: 1.0
  INTC.NAS: 1
  INTU.NAS: 1
  IOTAUSD: 250.0
  ISP.MIL: 18.01802
  ISRG.NAS: 1
  ITX.BM: 4.50083
  JAR.SGX: 3.85813
  JD.NAS: 3.0
  JNJ.NYSE: 3.0
  JPM.NYSE: 1.0
  JPN225: 0.01
  KEE.TSE: 0.007
  KO.NYSE: 3.0
  LI.NAS: 2.0
  LIN.NYSE: 1
  LINKUSD: 5.0
  LLY.NYSE: 1
  LMT.NYSE: 1
  LRCUSD: 575.0
  LSEG.LSE: 1.33217
  LTCUSD: 1.0
  MA.NYSE: 1
  MANAUSD: 170.14218
  MBG.XE: 3.0
  MC.EPA: 1.12534
  MCD.NYSE: 1.0
  MDLZ.NAS: 4.0
  META.NAS: 1
  MMM.NYSE: 1.0
  MRK.NYSE: 5.0
  MRK.XE: 4.0
  MS.NYSE: 1.0
  MSFT.NAS: 1
  MUR.TSE: 0.06901
  NAB.ASX: 5.13793
  NAS100: 0.1
  NEARUSD: 25.0
  NEE.NYSE: 3.0
  NESTE.OMXH: 7.86982
  NFLX.NAS: 1
  NID.TSE: 0.02068
  NKE.NYSE: 1.0
  NOKIA.OMXH: 14.59603
  NOW.NYSE: 1
  NVDA.NAS: 1.0
  NZDCAD: 717.4038
  NZDCHF: 1201.03093
  NZDJPY: 6.8757
  NZDUSD: 1000.0
  OL.TSE: 0.007
  OR.EPA: 1.12551
  ORCL.NYSE: 1.0
  PEP.NAS: 10.0
  PFE.NYSE: 3.0
  PG.NYSE: 2.0
  PM.NYSE: 1
  PYPL.NAS: 1.0
  QCOM.NAS: 2.0
  RACE.MIL: 1.11
  RMS.EPA: 1.11
  RTX.NYSE: 1.0
  SAN.BM: 15.87527
  SAP.NYSE: 1
  SBUX.NAS: 2.0
  SHEL.LSE: 2.65169
  SHOP.NYSE: 1.0
  SIE.XE: 1
  SOLUSD: 1
  SONY.NYSE: 5.0
  SPX500: 0.1
  STLA.MIL: 7.91667
  SUIUSD: 30.05115
  SVN.TSE: 0.06809
  T.NYSE: 4.0
  TCEHY.OTC: 2.0038
  TKY.TSE: 0.007
  TM.TSE: 0.07578
  TMH.TSE: 0.007
  TMO.NYSE: 1.0
  TMUS.NAS: 1
  TRXUSD: 1000
  TSLA.NAS: 1
  TTE.EPA: 11.25419
  TXN.NAS: 1.0
  UCG.MIL: 0.71429
  UK100: 0.13309
  ULVR.LSE: 1.34
  UNH.NYSE: 1.0
  UNIUSD: 10.0
  UNP.NYSE: 1.0
  UPS.NYSE: 15.0
  US30: 0.14
  USDCAD: 717.08923
  USDCHF: 1202.34114
  USDJPY: 6.88297
  USDMXN: 51.43678
  USDZAR: 54.92639
  V.NYSE: 1
  VNA.XE: 1.9962
  VOW3.XE: 1.0
  VZ.NYSE: 3.0
  WES.ASX: 1.92308
  WFC.NYSE: 2.0
  WMT.NYSE: 3.0
  XAGUSD: 50
  XAUUSD: 1
  XBRUSD: 10
  XNGUSD: 100
  XOM.NYSE: 2.0
  XRPUSD: 600
  XTIUSD: 10
  ZECUSD: 1.0
symbols_yfinance:
  AAPL.NAS: AAPL
  AAVEUSD: AAVE-USD
  ABBV.NYSE: ABBV
  ABNB.NAS: ABNB
  ABT.NYSE: ABT
  ACN.NYSE: ACN
  ADAUSD: ADA-USD
  ADBE.NAS: ADBE
  ADS.XE: ADS.DE
  AI.EPA: AI.PA
  AIR.EPA: AIR.PA
  ALGOUSD: ALGO-USD
  ALV.XE: ALV.DE
  AMD.NAS: AMD
  AMZN.NAS: AMZN
  APTUSD: APT21794-USD
  ASML.EAS: ASML.AS
  ATOMUSD: ATOM-USD
  AUDCAD: AUDCAD=X
  AUDCHF: AUDCHF=X
  AUDJPY: AUDJPY=X
  AUDNZD: AUDNZD=X
  AUDUSD: AUDUSD=X
  AUS200: ^AXJO
  AVAXUSD: AVAX-USD
  AVGO.NAS: AVGO
  AXP.NYSE: AXP
  AXSUSD: AXS-USD
  AZN.LSE: AZN.L
  BA.NYSE: BA
  BABA.NYSE: BABA
  BAC.NYSE: BAC
  BARC.LSE: BARC.L
  BATS.LSE: BATS.L
  BAYN.FWB: BAYN.DE
  BBVA.BM: BBVA.MC
  BCHUSD: BCH-USD
  BEI.XE: BEI.DE
  BHP.ASX: BHP.AX
  BKNG.NAS: BKNG
  BLK.NYSE: BLK
  BMW.XE: BMW.DE
  BMY.NYSE: BMY
  BNBUSD: BNB-USD
  BNP.EPA: BNP.PA
  BTCUSD: BTC-USD
  BX.NYSE: BX
  CABK.BM: CABK.MC
  CADCHF: CADCHF=X
  CADJPY: CADJPY=X
  CAT.NYSE: CAT
  CBA.ASX: CBA.AX
  CHFJPY: CHFJPY=X
  CMCSA.NAS: CMCSA
  COP.NYSE: COP
  COST.NAS: COST
  CPTL.SGX: 9CI.SI
  CRM.NYSE: CRM
  CSCO.NAS: CSCO
  CSL.ASX: CSL.AX
  CVS.NYSE: CVS
  CVX.NYSE: CVX
  DAII.TSE: 4568.T
  DASHUSD: DASH-USD
  DHR.NYSE: DHR
  DIS.NYSE: DIS
  DKI.TSE: 6367.T
  DOGEUSD: DOGE-USD
  DOTUSD: DOT-USD
  DTE.FWB: DTE.DE
  DTG.FWB: DTG.DE
  ENEL.MIL: ENEL.MI
  ENI.MIL: ENI.MI
  ESP35: ^IBEX
  ETCUSD: ETC-USD
  ETHUSD: ETH-USD
  EURAUD: EURAUD=X
  EURCAD: EURCAD=X
  EURCHF: EURCHF=X
  EURGBP: EURGBP=X
  EURJPY: EURJPY=X
  EURMXN: EURMXN=X
  EURNZD: EURNZD=X
  EURUSD: EURUSD=X
  EURZAR: EURZAR=X
  EUSTX50: ^STOXX50E
  FETUSD: FET-USD
  FILUSD: FIL-USD
  FRA40: ^FCHI
  GBPAUD: GBPAUD=X
  GBPCAD: GBPCAD=X
  GBPCHF: GBPCHF=X
  GBPJPY: GBPJPY=X
  GBPMXN: GBPMXN=X
  GBPNZD: GBPNZD=X
  GBPUSD: GBPUSD=X
  GBPZAR: GBPZAR=X
  GE.NYSE: GE
  GER40: ^GDAXI
  GOOGL.NAS: GOOGL
  GS.NYSE: GS
  HD.NYSE: HD
  HEIA.EAS: HEIA.AS
  HIT.TSE: 6501.T
  HMC.NYSE: HMC
  HON.NAS: HON
  HSBA.LSE: HSBA.L
  IBM.NYSE: IBM
  INTC.NAS: INTC
  INTU.NAS: INTU
  IOTAUSD: IOTA-USD
  ISP.MIL: ISP.MI
  ISRG.NAS: ISRG
  ITX.BM: ITX.MC
  JAR.SGX: C07.SI
  JD.NAS: JD
  JNJ.NYSE: JNJ
  JPM.NYSE: JPM
  JPN225: ^N225
  KEE.TSE: 6861.T
  KO.NYSE: KO
  LI.NAS: LI
  LIN.NYSE: LIN
  LINKUSD: LINK-USD
  LLY.NYSE: LLY
  LMT.NYSE: LMT
  LRCUSD: LRC-USD
  LSEG.LSE: LSEG.L
  LTCUSD: LTC-USD
  MA.NYSE: MA
  MANAUSD: MANA-USD
  MBG.XE: MBG.DE
  MC.EPA: MC.PA
  MCD.NYSE: MCD
  MDLZ.NAS: MDLZ
  META.NAS: META
  MMM.NYSE: MMM
  MRK.NYSE: MRK
  MRK.XE: MRK.DE
  MS.NYSE: MS
  MSFT.NAS: MSFT
  MUR.TSE: 6981.T
  NAB.ASX: NAB.AX
  NAS100: ^IXIC
  NEARUSD: NEAR-USD
  NEE.NYSE: NEE
  NESTE.OMXH: NESTE.HE
  NFLX.NAS: NFLX
  NID.TSE: 6594.T
  NKE.NYSE: NKE
  NOKIA.OMXH: NOKIA.HE
  NOW.NYSE: NOW
  NVDA.NAS: NVDA
  NZDCAD: NZDCAD=X
  NZDCHF: NZDCHF=X
  NZDJPY: NZDJPY=X
  NZDUSD: NZDUSD=X
  OL.TSE: 4661.T
  OR.EPA: OR.PA
  ORCL.NYSE: ORCL
  PEP.NAS: PEP
  PFE.NYSE: PFE
  PG.NYSE: PG
  PM.NYSE: PM
  PYPL.NAS: PYPL
  QCOM.NAS: QCOM
  RACE.MIL: RACE.MI
  RMS.EPA: RMS.PA
  RTX.NYSE: RTX
  SAN.BM: SAN.MC
  SAP.NYSE: SAP
  SBUX.NAS: SBUX
  SHEL.LSE: SHEL.L
  SHOP.NYSE: SHOP
  SIE.XE: SIE.DE
  SOLUSD: SOL-USD
  SONY.NYSE: SONY
  SPX500: ^GSPC
  STLA.MIL: STLAM.MI
  SUIUSD: SUI20947-USD
  SVN.TSE: 3382.T
  T.NYSE: T
  TCEHY.OTC: TCEHY
  TKY.TSE: 8035.T
  TM.TSE: 7203.T
  TMH.TSE: 8766.T
  TMO.NYSE: TMO
  TMUS.NAS: TMUS
  TRXUSD: TRX-USD
  TSLA.NAS: TSLA
  TTE.EPA: TTE.PA
  TXN.NAS: TXN
  UCG.MIL: UCG.MI
  UK100: ^FTSE
  UNH.NYSE: UNH
  UNIUSD: UNI1-USD
  UNP.NYSE: UNP
  UPS.NYSE: UPS
  US30: ^DJI
  USDCAD: CAD=X
  USDCHF: CHF=X
  USDJPY: JPY=X
  USDMXN: MXN=X
  USDZAR: ZAR=X
  V.NYSE: V
  VNA.XE: VNA.DE
  VOW3.XE: VOW3.DE
  VZ.NYSE: VZ
  WES.ASX: WES.AX
  WFC.NYSE: WFC
  WMT.NYSE: WMT
  XAGUSD: SI=F
  XAUUSD: GC=F
  XBRUSD: BZ=F
  XNGUSD: NG=F
  XOM.NYSE: XOM
  XRPUSD: XRP-USD
  XTIUSD: CL=F
  ZECUSD: ZEC-USD
tp_percent: 1.0
