daily_interval: 1d
daily_period: 30y
fetch_mt5: true
initial_balance: 1000
invest_per_week: 100
leverage: 1000
min_years_required: 1
output_directory: .
std_multiplier: 2
symbol_coefficients:
  AAPL.NAS: 1.0
  AAVEUSD: 0.5
  ABBV.NYSE: 1.0
  ABNB.NAS: 1.0
  ABT.NYSE: 1.0
  ACN.NYSE: 1.0
  ADAUSD: 100.0
  ADBE.NAS: 1.0
  ADS.XE: 1.00007
  AI.EPA: 1.14327
  AIR.EPA: 1.14317
  ALGOUSD: 25.00389
  ALV.XE: 1
  AMD.NAS: 1.0
  AMZN.NAS: 1.0
  APTUSD: 2.99983
  ASML.EAS: 1.1
  ATOMUSD: 2.50104
  AUDCAD: 730.80123
  AUDCHF: 1216.16358
  AUDJPY: 6.9037
  AUDNZD: 604.79775
  AUDUSD: 1000.0
  AUS200: 0.06549
  AVAXUSD: 1.0002
  AVGO.NAS: 1.0
  AXP.NYSE: 1.0
  AXSUSD: 0.5
  AZN.LSE: 1.25
  BA.NYSE: 1.0
  BABA.NYSE: 1.0
  BAC.NYSE: 1.0
  BARC.LSE: 1.35185
  BATS.LSE: 1.34494
  BAYN.FWB: 1.0
  BBVA.BM: 1.1462
  BCHUSD: 0.09995
  BEI.XE: 1.00119
  BHP.ASX: 0.65259
  BKNG.NAS: 1
  BLK.NYSE: 1
  BMW.XE: 1.00158
  BMY.NYSE: 1.0
  BNBUSD: 0.09984
  BNP.EPA: 1.14571
  BTCUSD: 0.01
  BX.NYSE: 1.0
  CABK.BM: 1.08
  CADCHF: 1216.77419
  CADJPY: 6.91044
  CAT.NYSE: 1.0
  CBA.ASX: 0.65517
  CHFJPY: 6.91489
  CMCSA.NAS: 1.0
  COP.NYSE: 1.0
  COST.NAS: 1
  CPTL.SGX: 0.76
  CRM.NYSE: 1.0
  CSCO.NAS: 1.0
  CSL.ASX: 0.65249
  CVS.NYSE: 1.0
  CVX.NYSE: 1.0
  DAII.TSE: 0.00697
  DASHUSD: 1.0
  DHR.NYSE: 1.0
  DIS.NYSE: 1.0
  DKI.TSE: 0.0069
  DOGEUSD: 1000
  DOTUSD: 2.5
  DTE.FWB: 1.0
  DTG.FWB: 18
  ENEL.MIL: 1.14321
  ENI.MIL: 1.14407
  ESP35: 0.1
  ETCUSD: 2.50323
  ETHUSD: 0.1
  EURAUD: 652.62779
  EURCAD: 730.62589
  EURCHF: 1216.58031
  EURGBP: 1352.09446
  EURJPY: 6.90165
  EURMXN: 52.47738
  EURNZD: 604.87517
  EURUSD: 1000.0
  EURZAR: 56.49744
  EUSTX50: 0.1
  FETUSD: 29.99767
  FILUSD: 0.99993
  FRA40: 0.11262
  GBPAUD: 652.24035
  GBPCAD: 732.21344
  GBPCHF: 1216.57754
  GBPJPY: 6.90383
  GBPMXN: 52.48338
  GBPNZD: 603.13009
  GBPUSD: 1000.0
  GBPZAR: 56.49091
  GE.NYSE: 1
  GER40: 0.1
  GOOGL.NAS: 1.0
  GS.NYSE: 1
  HD.NYSE: 1.0
  HEIA.EAS: 1.14322
  HIT.TSE: 0.00691
  HMC.NYSE: 1.0
  HON.NAS: 1.0
  HSBA.LSE: 1.34959
  IBM.NYSE: 1.0
  INTC.NAS: 1.0
  INTU.NAS: 1
  IOTAUSD: 50.02633
  ISP.MIL: 1.14407
  ISRG.NAS: 1
  ITX.BM: 1.13953
  JAR.SGX: 0.77778
  JD.NAS: 1.0
  JNJ.NYSE: 1.0
  JPM.NYSE: 1.0
  JPN225: 0.00691
  KEE.TSE: 0.0069
  KO.NYSE: 1.0
  LI.NAS: 1.0
  LIN.NYSE: 1.0
  LINKUSD: 2.5
  LLY.NYSE: 1.0
  LMT.NYSE: 1.0
  LRCUSD: 25.0
  LSEG.LSE: 1.34983
  LTCUSD: 1.0
  MA.NYSE: 1
  MANAUSD: 10.00559
  MBG.XE: 1.0
  MC.EPA: 1.1434
  MCD.NYSE: 1.0
  MDLZ.NAS: 1.0
  META.NAS: 1
  MMM.NYSE: 1.0
  MRK.NYSE: 1.0
  MRK.XE: 1.0
  MS.NYSE: 1.0
  MSFT.NAS: 1
  MUR.TSE: 0.0069
  NAB.ASX: 0.63636
  NAS100: 0.1
  NEARUSD: 2.5
  NEE.NYSE: 1.0
  NESTE.OMXH: 1.14286
  NFLX.NAS: 1
  NID.TSE: 0.00687
  NKE.NYSE: 1.0
  NOKIA.OMXH: 1.14802
  NOW.NYSE: 1
  NVDA.NAS: 1.0
  NZDCAD: 730.50312
  NZDCHF: 1216.0
  NZDJPY: 6.89617
  NZDUSD: 1000.0
  OL.TSE: 0.00696
  OR.EPA: 1.14343
  ORCL.NYSE: 1.0
  PEP.NAS: 1.0
  PFE.NYSE: 1.0
  PG.NYSE: 1.0
  PM.NYSE: 1.0
  PYPL.NAS: 1.0
  QCOM.NAS: 1.0
  RACE.MIL: 1.14231
  RMS.EPA: 1.11
  RTX.NYSE: 1.0
  SAN.BM: 1.13996
  SAP.NYSE: 1
  SBUX.NAS: 1.0
  SHEL.LSE: 1.35294
  SHOP.NYSE: 1.0
  SIE.XE: 0.99831
  SOLUSD: 1.0
  SONY.NYSE: 1.0
  SPX500: 0.1
  STLA.MIL: 1.14286
  SUIUSD: 29.99716
  SVN.TSE: 0.0069
  T.NYSE: 1.0
  TCEHY.OTC: 1.0
  TKY.TSE: 0.0069
  TM.TSE: 0.0069
  TMH.TSE: 0.00692
  TMO.NYSE: 1.0
  TMUS.NAS: 1.0
  TRXUSD: 1000
  TSLA.NAS: 1
  TTE.EPA: 1.14607
  TXN.NAS: 1.0
  UCG.MIL: 1.14309
  UK100: 0.13125
  ULVR.LSE: 1.34
  UNH.NYSE: 1.0
  UNIUSD: 2.50407
  UNP.NYSE: 1.0
  UPS.NYSE: 1.0
  US30: 0.14
  USDCAD: 730.88483
  USDCHF: 1215.51724
  USDJPY: 6.90324
  USDMXN: 52.48619
  USDZAR: 56.49708
  V.NYSE: 1.0
  VNA.XE: 1.00093
  VOW3.XE: 0.99967
  VZ.NYSE: 1.0
  WES.ASX: 0.65341
  WFC.NYSE: 1.0
  WMT.NYSE: 1.0
  XAGUSD: 50
  XAUUSD: 1
  XBRUSD: 10.0
  XNGUSD: 100.0
  XOM.NYSE: 1.0
  XRPUSD: 600
  XTIUSD: 10.0
  ZECUSD: 1.0
symbols_yfinance:
  AAPL.NAS: AAPL
  AAVEUSD: AAVE-USD
  ABBV.NYSE: ABBV
  ABNB.NAS: ABNB
  ABT.NYSE: ABT
  ACN.NYSE: ACN
  ADAUSD: ADA-USD
  ADBE.NAS: ADBE
  ADS.XE: ADS.DE
  AI.EPA: AI.PA
  AIR.EPA: AIR.PA
  ALGOUSD: ALGO-USD
  ALV.XE: ALV.DE
  AMD.NAS: AMD
  AMZN.NAS: AMZN
  APTUSD: APT21794-USD
  ASML.EAS: ASML.AS
  ATOMUSD: ATOM-USD
  AUDCAD: AUDCAD=X
  AUDCHF: AUDCHF=X
  AUDJPY: AUDJPY=X
  AUDNZD: AUDNZD=X
  AUDUSD: AUDUSD=X
  AUS200: ^AXJO
  AVAXUSD: AVAX-USD
  AVGO.NAS: AVGO
  AXP.NYSE: AXP
  AXSUSD: AXS-USD
  AZN.LSE: AZN.L
  BA.NYSE: BA
  BABA.NYSE: BABA
  BAC.NYSE: BAC
  BARC.LSE: BARC.L
  BATS.LSE: BATS.L
  BAYN.FWB: BAYN.DE
  BBVA.BM: BBVA.MC
  BCHUSD: BCH-USD
  BEI.XE: BEI.DE
  BHP.ASX: BHP.AX
  BKNG.NAS: BKNG
  BLK.NYSE: BLK
  BMW.XE: BMW.DE
  BMY.NYSE: BMY
  BNBUSD: BNB-USD
  BNP.EPA: BNP.PA
  BTCUSD: BTC-USD
  BX.NYSE: BX
  CABK.BM: CABK.MC
  CADCHF: CADCHF=X
  CADJPY: CADJPY=X
  CAT.NYSE: CAT
  CBA.ASX: CBA.AX
  CHFJPY: CHFJPY=X
  CMCSA.NAS: CMCSA
  COP.NYSE: COP
  COST.NAS: COST
  CPTL.SGX: 9CI.SI
  CRM.NYSE: CRM
  CSCO.NAS: CSCO
  CSL.ASX: CSL.AX
  CVS.NYSE: CVS
  CVX.NYSE: CVX
  DAII.TSE: 4568.T
  DASHUSD: DASH-USD
  DHR.NYSE: DHR
  DIS.NYSE: DIS
  DKI.TSE: 6367.T
  DOGEUSD: DOGE-USD
  DOTUSD: DOT-USD
  DTE.FWB: DTE.DE
  DTG.FWB: DTG.DE
  ENEL.MIL: ENEL.MI
  ENI.MIL: ENI.MI
  ESP35: ^IBEX
  ETCUSD: ETC-USD
  ETHUSD: ETH-USD
  EURAUD: EURAUD=X
  EURCAD: EURCAD=X
  EURCHF: EURCHF=X
  EURGBP: EURGBP=X
  EURJPY: EURJPY=X
  EURMXN: EURMXN=X
  EURNZD: EURNZD=X
  EURUSD: EURUSD=X
  EURZAR: EURZAR=X
  EUSTX50: ^STOXX50E
  FETUSD: FET-USD
  FILUSD: FIL-USD
  FRA40: ^FCHI
  GBPAUD: GBPAUD=X
  GBPCAD: GBPCAD=X
  GBPCHF: GBPCHF=X
  GBPJPY: GBPJPY=X
  GBPMXN: GBPMXN=X
  GBPNZD: GBPNZD=X
  GBPUSD: GBPUSD=X
  GBPZAR: GBPZAR=X
  GE.NYSE: GE
  GER40: ^GDAXI
  GOOGL.NAS: GOOGL
  GS.NYSE: GS
  HD.NYSE: HD
  HEIA.EAS: HEIA.AS
  HIT.TSE: 6501.T
  HMC.NYSE: HMC
  HON.NAS: HON
  HSBA.LSE: HSBA.L
  IBM.NYSE: IBM
  INTC.NAS: INTC
  INTU.NAS: INTU
  IOTAUSD: IOTA-USD
  ISP.MIL: ISP.MI
  ISRG.NAS: ISRG
  ITX.BM: ITX.MC
  JAR.SGX: C07.SI
  JD.NAS: JD
  JNJ.NYSE: JNJ
  JPM.NYSE: JPM
  JPN225: ^N225
  KEE.TSE: 6861.T
  KO.NYSE: KO
  LI.NAS: LI
  LIN.NYSE: LIN
  LINKUSD: LINK-USD
  LLY.NYSE: LLY
  LMT.NYSE: LMT
  LRCUSD: LRC-USD
  LSEG.LSE: LSEG.L
  LTCUSD: LTC-USD
  MA.NYSE: MA
  MANAUSD: MANA-USD
  MBG.XE: MBG.DE
  MC.EPA: MC.PA
  MCD.NYSE: MCD
  MDLZ.NAS: MDLZ
  META.NAS: META
  MMM.NYSE: MMM
  MRK.NYSE: MRK
  MRK.XE: MRK.DE
  MS.NYSE: MS
  MSFT.NAS: MSFT
  MUR.TSE: 6981.T
  NAB.ASX: NAB.AX
  NAS100: ^IXIC
  NEARUSD: NEAR-USD
  NEE.NYSE: NEE
  NESTE.OMXH: NESTE.HE
  NFLX.NAS: NFLX
  NID.TSE: 6594.T
  NKE.NYSE: NKE
  NOKIA.OMXH: NOKIA.HE
  NOW.NYSE: NOW
  NVDA.NAS: NVDA
  NZDCAD: NZDCAD=X
  NZDCHF: NZDCHF=X
  NZDJPY: NZDJPY=X
  NZDUSD: NZDUSD=X
  OL.TSE: 4661.T
  OR.EPA: OR.PA
  ORCL.NYSE: ORCL
  PEP.NAS: PEP
  PFE.NYSE: PFE
  PG.NYSE: PG
  PM.NYSE: PM
  PYPL.NAS: PYPL
  QCOM.NAS: QCOM
  RACE.MIL: RACE.MI
  RMS.EPA: RMS.PA
  RTX.NYSE: RTX
  SAN.BM: SAN.MC
  SAP.NYSE: SAP
  SBUX.NAS: SBUX
  SHEL.LSE: SHEL.L
  SHOP.NYSE: SHOP
  SIE.XE: SIE.DE
  SOLUSD: SOL-USD
  SONY.NYSE: SONY
  SPX500: ^GSPC
  STLA.MIL: STLAM.MI
  SUIUSD: SUI20947-USD
  SVN.TSE: 3382.T
  T.NYSE: T
  TCEHY.OTC: TCEHY
  TKY.TSE: 8035.T
  TM.TSE: 7203.T
  TMH.TSE: 8766.T
  TMO.NYSE: TMO
  TMUS.NAS: TMUS
  TRXUSD: TRX-USD
  TSLA.NAS: TSLA
  TTE.EPA: TTE.PA
  TXN.NAS: TXN
  UCG.MIL: UCG.MI
  UK100: ^FTSE
  UNH.NYSE: UNH
  UNIUSD: UNI1-USD
  UNP.NYSE: UNP
  UPS.NYSE: UPS
  US30: ^DJI
  USDCAD: CAD=X
  USDCHF: CHF=X
  USDJPY: JPY=X
  USDMXN: MXN=X
  USDZAR: ZAR=X
  V.NYSE: V
  VNA.XE: VNA.DE
  VOW3.XE: VOW3.DE
  VZ.NYSE: VZ
  WES.ASX: WES.AX
  WFC.NYSE: WFC
  WMT.NYSE: WMT
  XAGUSD: SI=F
  XAUUSD: GC=F
  XBRUSD: BZ=F
  XNGUSD: NG=F
  XOM.NYSE: XOM
  XRPUSD: XRP-USD
  XTIUSD: CL=F
  ZECUSD: ZEC-USD
tp_percent: 1.0
