symbols_yfinance:
  AUDUSD: "AUDUSD=X"
  EURUSD: "EURUSD=X"
  GBPUSD: "GBPUSD=X"
  NZDUSD: "NZDUSD=X"
  USDCAD: "CAD=X"
  USDCHF: "CHF=X"
  USDJPY: "JPY=X"
  XAUUSD: "GC=F"
  AUS200: "^AXJO"   # Australian ASX 200 Index
  ESP35: "^IBEX"    # Spanish IBEX 35 Index
  EUSTX50: "^STOXX50E"  # Euro Stoxx 50 Index
  FRA40: "^FCHI"    # French CAC 40 Index
  GER40: "^GDAXI"   # German DAX 40 Index
  JPN225: "^N225"   # Japanese Nikkei 225 Index
  NAS100: "^IXIC"   # NASDAQ 100 Index
  SPX500: "^GSPC"   # S&P 500 Index
  UK100: "^FTSE"    # UK FTSE 100 Index
  US30: "^DJI"      # US Dow Jones Industrial Average
  BAC.NYSE: "BAC"
  GS.NYSE: "GS"
  JPM.NYSE: "JPM"
  MS.NYSE: "MS"
  WFC.NYSE: "WFC"  
  CBA.ASX: "CBA.AX"
  NAB.ASX: "NAB.AX"
  BNP.EPA: "BNP.PA"
  BARC.LSE: "BARC.L"
  HSBA.LSE: "HSBA.L"
  ISP.MIL: "ISP.MI"
  UCG.MIL: "UCG.MI"
  BBVA.BM: "BBVA.MC"
  CABK.BM: "CABK.MC"
  SAN.BM: "SAN.MC"
  ADAUSD: "ADA-USD"
  AVAXUSD: "AVAX-USD"
  BNBUSD: "BNB-USD"
  BTCUSD: "BTC-USD"
  DOGEUSD: "DOGE-USD"
  ETHUSD: "ETH-USD"
  LINKUSD: "LINK-USD"
  SOLUSD: "SOL-USD"
  TRXUSD: "TRX-USD"
  XRPUSD: "XRP-USD"

symbol_coefficients:
  AUDUSD: 1000
  EURUSD: 1000
  GBPUSD: 1000
  NZDUSD: 1000
  USDCAD: 741.78
  USDCHF: 1135.87
  USDJPY: 6.99
  XAUUSD: 1
  JPN225: 0.01
  AUS200: 0.06
  SPX500: 0.10
  EUSTX50: 0.10
  UK100: 0.12
  NAS100: 0.10
  FRA40: 0.10
  GER40: 0.10
  ESP35: 0.10
  US30: 0.14
  BAC.NYSE: 1
  GS.NYSE: 1
  JPM.NYSE: 1
  MS.NYSE: 1
  WFC.NYSE: 1  
  CBA.ASX: 0.6
  NAB.ASX: 0.6
  BNP.EPA: 2.19
  BARC.LSE: 1.29
  HSBA.LSE: 1.29
  ISP.MIL: 1.08
  UCG.MIL: 1.08
  BBVA.BM: 1.08
  CABK.BM: 1.08
  SAN.BM: 1.08
  ADAUSD: 100
  AVAXUSD: 1.01
  BNBUSD: 0.1
  BTCUSD: 0.01
  DOGEUSD: 1000
  ETHUSD: 0.1
  LINKUSD: 2.5
  SOLUSD: 1
  TRXUSD: 1000
  XRPUSD: 600


  

daily_period: "30y"   # Fetch daily-level data for the past 10 years
daily_interval: "1d"  # Use 1-day interval for historical daily data
output_directory: "."  # Directory where CSV files will be saved
std_multiplier: 3 # 68% within ±1σ, 75% within ±1.15σ, 80% within ±1.28σ, 85% within ±1.44σ, 90% within ±1.645σ, 95% within ±1.96σ, 99% within ±2.576σ, 99.7% within ±3σ, and 99.9% within ±3.291σ.