symbols_yfinance:
  AUDCAD: "AUDCAD=X"
  AUDCHF: "AUDCHF=X"
  AUDJPY: "AUDJPY=X"
  AUDNZD: "AUDNZD=X"
  AUDUSD: "AUDUSD=X"
  CADCHF: "CADCHF=X"
  CADJPY: "CADJPY=X"
  CHFJPY: "CHFJPY=X"
  EURAUD: "EURAUD=X"
  EURCAD: "EURCAD=X"
  EURCHF: "EURCHF=X"
  EURGBP: "EURGBP=X"
  EURJPY: "EURJPY=X"
  EURMXN: "EURMXN=X"
  EURNZD: "EURNZD=X"
  EURUSD: "EURUSD=X"
  EURZAR: "EURZAR=X"
  GBPAUD: "GBPAUD=X"
  GBPCAD: "GBPCAD=X"
  GBPCHF: "GBPCHF=X"
  GBPJPY: "GBPJPY=X"
  GBPMXN: "GBPMXN=X"
  GBPNZD: "GBPNZD=X"
  GBPUSD: "GBPUSD=X"
  GBPZAR: "GBPZAR=X"
  NZDCAD: "NZDCAD=X"
  NZDCHF: "NZDCHF=X"
  NZDJPY: "NZDJPY=X"
  NZDUSD: "NZDUSD=X"
  ZARJPY: "ZARJPY=X"
  USDCAD: "CAD=X"
  USDCHF: "CHF=X"
  USDJPY: "JPY=X"
  USDMXN: "MXN=X"
  USDZAR: "ZAR=X"
  XAGUSD: "SI=F"
  XAUUSD: "GC=F"
  XBRUSD: "BZ=F"
  XNGUSD: "NG=F"
  XTIUSD: "CL=F"
  AUS200: "^AXJO"   # Australian ASX 200 Index
  ESP35: "^IBEX"    # Spanish IBEX 35 Index
  EUSTX50: "^STOXX50E"  # Euro Stoxx 50 Index
  FRA40: "^FCHI"    # French CAC 40 Index
  GER40: "^GDAXI"   # German DAX 40 Index
  JPN225: "^N225"   # Japanese Nikkei 225 Index
  NAS100: "^IXIC"   # NASDAQ 100 Index
  SPX500: "^GSPC"   # S&P 500 Index
  UK100: "^FTSE"    # UK FTSE 100 Index
  US30: "^DJI"      # US Dow Jones Industrial Average
  ABBV.NYSE: "ABBV"
  AAPL.NAS: "AAPL"
  ABNB.NAS: "ABNB"
  ABT.NYSE: "ABT"
  ACN.NYSE: "ACN"
  ADBE.NAS: "ADBE"
  AMD.NAS: "AMD"
  AMZN.NAS: "AMZN"
  AVGO.NAS: "AVGO"
  AXP.NYSE: "AXP"
  BA.NYSE: "BA"
  BABA.NYSE: "BABA"
  BAC.NYSE: "BAC"
  BKNG.NAS: "BKNG"
  BLK.NYSE: "BLK"
  BMY.NYSE: "BMY"
  BX.NYSE: "BX"
  CAT.NYSE: "CAT"
  CMCSA.NAS: "CMCSA"
  COP.NYSE: "COP"
  COST.NAS: "COST"
  CRM.NYSE: "CRM"
  CSCO.NAS: "CSCO"
  CVS.NYSE: "CVS"
  CVX.NYSE: "CVX"
  DHR.NYSE: "DHR"
  DIS.NYSE: "DIS"
  GE.NYSE: "GE"
  GOOGL.NAS: "GOOGL"
  GS.NYSE: "GS"
  HD.NYSE: "HD"
  HMC.NYSE: "HMC"
  HON.NAS: "HON"
  IBM.NYSE: "IBM"
  INTC.NAS: "INTC"
  INTU.NAS: "INTU"
  ISRG.NAS: "ISRG"
  JD.NAS: "JD"
  JPM.NYSE: "JPM"
  JNJ.NYSE: "JNJ"
  KO.NYSE: "KO"
  LI.NAS: "LI"
  LIN.NYSE: "LIN"
  LLY.NYSE: "LLY"
  LMT.NYSE: "LMT"
  MA.NYSE: "MA"
  MCD.NYSE: "MCD"
  MDLZ.NAS: "MDLZ"
  META.NAS: "META"
  MMM.NYSE: "MMM"
  MRK.NYSE: "MRK"
  MS.NYSE: "MS"
  MSFT.NAS: "MSFT"
  NEE.NYSE: "NEE"
  NFLX.NAS: "NFLX"
  NKE.NYSE: "NKE"
  NOW.NYSE: "NOW"
  NVDA.NAS: "NVDA"
  ORCL.NYSE: "ORCL"
  PEP.NAS: "PEP"
  PFE.NYSE: "PFE"
  PG.NYSE: "PG"
  PM.NYSE: "PM"
  PYPL.NAS: "PYPL"
  QCOM.NAS: "QCOM"
  RTX.NYSE: "RTX"
  SAP.NYSE: "SAP"
  SBUX.NAS: "SBUX"
  SHOP.NYSE: "SHOP"
  SONY.NYSE: "SONY"
  T.NYSE: "T"
  TMO.NYSE: "TMO"
  TMUS.NAS: "TMUS"
  TSLA.NAS: "TSLA"
  TXN.NAS: "TXN"
  UNH.NYSE: "UNH"
  UNP.NYSE: "UNP"
  UPS.NYSE: "UPS"
  V.NYSE: "V"
  VZ.NYSE: "VZ"
  WMT.NYSE: "WMT"
  XOM.NYSE: "XOM"
  WFC.NYSE: "WFC"  
  BHP.ASX: "BHP.AX"
  CBA.ASX: "CBA.AX"
  CSL.ASX: "CSL.AX"
  NAB.ASX: "NAB.AX"
  WES.ASX: "WES.AX"
  AI.EPA: "AI.PA"
  AIR.EPA: "AIR.PA"
  BNP.EPA: "BNP.PA"
  MC.EPA: "MC.PA"
  OR.EPA: "OR.PA"
  RMS.EPA: "RMS.PA"
  TTE.EPA: "TTE.PA"
  AZN.LSE: "AZN.L"
  BARC.LSE: "BARC.L"
  BATS.LSE: "BATS.L"
  HSBA.LSE: "HSBA.L"
  LSEG.LSE: "LSEG.L"
  SHEL.LSE: "SHEL.L"
  ENEL.MIL: "ENEL.MI"
  ENI.MIL: "ENI.MI"
  ISP.MIL: "ISP.MI"
  RACE.MIL: "RACE.MI"
  STLA.MIL: "STLAM.MI"
  UCG.MIL: "UCG.MI"
  BBVA.BM: "BBVA.MC"
  CABK.BM: "CABK.MC"
  ITX.BM: "ITX.MC"
  SAN.BM: "SAN.MC"
  ADS.XE: "ADS.DE"
  ALV.XE: "ALV.DE"
  BAYN.FWB: "BAYN.DE"
  BEI.XE: "BEI.DE"
  BMW.XE: "BMW.DE"
  DTE.FWB: "DTE.DE"
  DTG.FWB: "DTG.DE"
  MBG.XE: "MBG.DE"
  MRK.XE: "MRK.DE"
  SIE.XE: "SIE.DE"
  VNA.XE: "VNA.DE"
  VOW3.XE: "VOW3.DE"
  ASML.EAS: "ASML.AS"
  HEIA.EAS: "HEIA.AS"
  CPTL.SGX: "9CI.SI"
  JAR.SGX: "C07.SI"
  DAII.TSE: "4568.T"
  DKI.TSE: "6367.T"
  HIT.TSE: "6501.T"
  KEE.TSE: "6861.T"
  MUR.TSE: "6981.T"
  NID.TSE: "6594.T"
  OL.TSE: "4661.T"
  SVN.TSE: "3382.T"
  TKY.TSE: "8035.T"
  TM.TSE: "7203.T"
  TMH.TSE: "8766.T"
  NESTE.OMXH: "NESTE.HE"
  NOKIA.OMXH: "NOKIA.HE"
  TCEHY.OTC: "TCEHY"
  AAVEUSD: "AAVE-USD"
  ADAUSD: "ADA-USD"
  ALGOUSD: "ALGO-USD"
  APTUSD: "APT21794-USD"
  ARBUSD: "ARB11841-USD"
  ATOMUSD: "ATOM-USD"
  AVAXUSD: "AVAX-USD"
  AXSUSD: "AXS-USD"
  BCHUSD: "BCH-USD"
  BNBUSD: "BNB-USD"
  BTCUSD: "BTC-USD"
  DASHUSD: "DASH-USD"
  DOGEUSD: "DOGE-USD"
  DOTUSD: "DOT-USD"
  ETCUSD: "ETC-USD"
  ETHUSD: "ETH-USD"
  FETUSD: "FET-USD"
  FILUSD: "FIL-USD"
  GRTUSD: "GRT1-USD"
  ICPUSD: "ICP-USD"
  IOTAUSD: "IOTA-USD"
  LINKUSD: "LINK-USD"
  LRCUSD: "LRC-USD"
  LTCUSD: "LTC-USD"
  MANAUSD: "MANA-USD"
  NEARUSD: "NEAR-USD"
  SOLUSD: "SOL-USD"
  SUIUSD: "SUI20947-USD"
  TRXUSD: "TRX-USD"
  UNIUSD: "UNI1-USD"
  XRPUSD: "XRP-USD"
  ZECUSD: "ZEC-USD"

symbol_coefficients:
  AUDCAD: 740.21
  AUDCHF: 1181.82
  AUDJPY: 6.97
  AUDNZD: 628.42
  AUDUSD: 1000
  CADCHF: 1178.68
  CADJPY: 6.99
  CHFJPY: 6.98
  EURAUD: 686.89
  EURCAD: 740.05
  EURCHF: 1183.34
  EURGBP: 1326.53
  EURJPY: 6.97
  EURMXN: 50.95
  EURNZD: 628.29
  EURUSD: 1000
  EURZAR: 57.61
  GBPAUD: 687.32
  GBPCAD: 741.40
  GBPCHF: 1180.65
  GBPJPY: 6.97
  GBPMXN: 50.95
  GBPNZD: 615.38
  GBPUSD: 1000
  GBPZAR: 57.24
  NZDCAD: 740.56
  NZDCHF: 1181.65
  NZDJPY: 6.97
  NZDUSD: 1000
  USDCAD: 741.78
  USDCHF: 1135.87
  USDJPY: 6.99
  USDMXN: 50.45
  USDZAR: 57.49
  ZARJPY: 6.89
  XAGUSD: 50
  XAUUSD: 1
  XBRUSD: 10
  XNGUSD: 100
  XTIUSD: 10
  AUS200: 0.06
  ESP35: 0.10
  EUSTX50: 0.10
  FRA40: 0.10
  GER40: 0.10
  JPN225: 0.01
  NAS100: 0.10
  SPX500: 0.10
  UK100: 0.12
  US30: 0.14
  AAPL.NAS: 1

  VOD.LSE: 
  HK.SGX: 
  SGX.SGX: 
  SIAIR.SGX:
  WLMR.SGX:
  VOLVA.SOMX:

  ABBV.NYSE: 1
  AAPL.NAS: 1
  ABNB.NAS: 1
  ABT.NYSE: 1
  ACN.NYSE: 1
  ADBE.NAS: 1
  AMD.NAS: 1
  AMZN.NAS: 1
  AVGO.NAS: 1
  AXP.NYSE: 1
  BA.NYSE: 1
  BABA.NYSE: 1
  BAC.NYSE: 1
  BKNG.NAS: 1
  BLK.NYSE: 1
  BMY.NYSE: 1
  BX.NYSE: 1
  CAT.NYSE: 1
  CMCSA.NAS: 1
  COP.NYSE: 1
  COST.NAS: 1
  CRM.NYSE: 1
  CSCO.NAS: 1
  CVS.NYSE: 1
  CVX.NYSE: 1
  DHR.NYSE: 1
  DIS.NYSE: 1
  GE.NYSE: 1
  GOOGL.NAS: 1
  GS.NYSE: 1
  HD.NYSE: 1
  HMC.NYSE: 1
  HON.NAS: 1
  IBM.NYSE: 1
  INTC.NAS: 1
  INTU.NAS: 1
  ISRG.NAS: 1
  JD.NAS: 1
  JPM.NYSE: 1
  JNJ.NYSE: 1
  KO.NYSE: 1
  LI.NAS: 1
  LIN.NYSE: 1
  LLY.NYSE: 1
  LMT.NYSE: 1
  MA.NYSE: 1
  MCD.NYSE: 1
  MDLZ.NAS: 1
  META.NAS: 1
  MMM.NYSE: 1
  MRK.NYSE: 1
  MS.NYSE: 1
  MSFT.NAS: 1
  NEE.NYSE: 1
  NFLX.NAS: 1
  NKE.NYSE: 1
  NOW.NYSE: 1
  NVDA.NAS: 1
  ORCL.NYSE: 1
  PEP.NAS: 1
  PFE.NYSE: 1
  PG.NYSE: 1
  PM.NYSE: 1
  PYPL.NAS: 1
  QCOM.NAS: 1
  RTX.NYSE: 1
  SAP.NYSE: 1
  SBUX.NAS: 1
  SHOP.NYSE: 1
  SONY.NYSE: 1
  T.NYSE: 1  
  TMO.NYSE: 1
  TMUS.NAS: 1
  TSLA.NAS: 1
  TXN.NAS: 1
  UNH.NYSE: 1
  UNP.NYSE: 1
  UPS.NYSE: 1
  V.NYSE: 1  
  VZ.NYSE: 1
  WMT.NYSE: 1
  XOM.NYSE: 1
  WFC.NYSE: 1  
  BHP.ASX: 0.69
  CBA.ASX: 0.6
  NAB.ASX: 0.6
  CSL.ASX: 0.7
  WES.ASX: 0.69
  AI.EPA: 1.11
  AIR.EPA: 1.11
  BNP.EPA: 2.19
  MC.EPA: 1.11
  OR.EPA: 1.11
  RMS.EPA: 1.11
  TTE.EPA: 1.11
  AZN.LSE: 1.33
  BARC.LSE: 1.29
  BATS.LSE: 1.34
  HSBA.LSE: 1.29
  LSEG.LSE: 1.25
  SHEL.LSE: 1.33
  ULVR.LSE: 1.34
  ENEL.MIL: 9.78
  ENI.MIL: 1.13
  ISP.MIL: 1.08
  RACE.MIL: 1.11
  STLA.MIL: 1.09
  UCG.MIL: 1.08
  BBVA.BM: 1.08
  CABK.BM: 1.08
  ITX.BM: 1.11
  SAN.BM: 1.08
  ADS.XE: 0.93
  ALV.XE: 1
  BAYN.FWB: 1
  BEI.XE: 3
  BMW.XE: 1.01
  DTE.FWB: 1
  DTG.FWB: 18
  MBG.XE: 1
  MRK.XE: 1
  SIE.XE: 1
  VNA.XE: 1
  VOW3.XE: 1
  ASML.EAS: 1.1
  HEIA.EAS: 1.11
  CPTL.SGX: 0.76
  JAR.SGX: 0.78
  DAII.TSE: 0.007
  DKI.TSE: 0.007
  HIT.TSE: 0.007
  KEE.TSE: 0.007
  MUR.TSE: 0.007
  NID.TSE: 0.007
  OL.TSE: 0.007
  SVN.TSE: 0.007
  TKY.TSE: 0.007
  TM.TSE: 0.007
  TMH.TSE: 0.007
  NESTE.OMXH: 1.11
  NOKIA.OMXH: 1.13
  TCEHY.OTC: 1
  AAVEUSD: 0.5
  ADAUSD: 100
  ALGOUSD: 25.29
  APTUSD: 3
  ARBUSD: 30.07
  ATOMUSD: 2.49
  AVAXUSD: 1.01
  AXSUSD: 0.5
  BCHUSD: 0.1
  BNBUSD: 0.1
  BTCUSD: 0.01
  DASHUSD: 1
  DOGEUSD: 1000
  DOTUSD: 2.55
  ETCUSD: 2.5
  ETHUSD: 0.1
  FETUSD: 30.03
  FILUSD: 1
  GRTUSD: 100
  ICPUSD: 1
  IOTAUSD: 50
  LINKUSD: 2.5
  LRCUSD: 25.12
  LTCUSD: 1
  MANAUSD: 9.91
  NEARUSD: 2.1
  SOLUSD: 1
  SUIUSD: 29.96
  TRXUSD: 1000
  UNIUSD: 2.5
  XRPUSD: 600
  ZECUSD: 1


  

daily_period: "30y"   # Fetch daily-level data for the past 10 years
daily_interval: "1d"  # Use 1-day interval for historical daily data
output_directory: "."  # Directory where CSV files will be saved
std_multiplier: 3 # 68% within ±1σ, 75% within ±1.15σ, 80% within ±1.28σ, 85% within ±1.44σ, 90% within ±1.645σ, 95% within ±1.96σ, 99% within ±2.576σ, 99.7% within ±3σ, and 99.9% within ±3.291σ.