name: Run Main Script Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  run-overview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install -r requirements.txt || echo "requirements.txt not found, skipping"

      - name: Run main.py
        run: python main.py